on:
  release:
    types: [created]
  push:

permissions:
  contents: write
  packages: write

jobs:
  linux:
    name: Release Linux Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install webview dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libwebkit2gtk-4.1-dev
      - name: Build
        run: |
          go build -ldflags="-s -w" -o bin/sage-linux-amd64 .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sage-linux-amd64
          path: ./bin/sage-linux-*
          if-no-files-found: error
      - if: github.event_name == 'release'
        name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./bin/sage-linux-*
          file_glob: true

  windows:
    name: Release Windows Binary
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Get RSVC
        run: |
          go install github.com/akavel/rsrc
      - name: Combine Windows resources
        run: |
          rsrc -manifest assets/windows/manifest.xml -ico assets/windows/icon.ico -o sage.syso
          cat sage.syso
      - name: Build
        run: |
          go build -ldflags="-s -w" -o bin/sage-windows-amd64.exe .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sage-windows-amd64
          path: ./bin/sage-windows-*
          if-no-files-found: error
      - if: github.event_name == 'release'
        name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./bin/sage-windows-*
          file_glob: true

  darwin:
    strategy:
      matrix:
        include:
          - runs-on: macos-13
            arch: amd64
          - runs-on: macos-14
            arch: arm64

    name: Release Darwin ${{ matrix.arch }} Binary
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Build
        run: |
          go build -ldflags="-s -w" -o bin/sage-darwin-${{ matrix.arch }} -tags CI .
      - name: Package
        run: |
          mkdir -p SAGE.app/Contents/MacOS SAGE.app/Contents/Resources
          cp bin/sage-darwin-${{ matrix.arch }} SAGE.app/Contents/MacOS/SAGE
          cp assets/darwin/Info.plist SAGE.app/Contents/Info.plist
          cp assets/darwin/icon.icns SAGE.app/Contents/Resources/icon.icns
          tar -czf bin/sage-darwin-${{ matrix.arch }}.app.tar.gz SAGE.app
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sage-darwin-${{ matrix.arch }}
          path: ./bin/sage-darwin-*
          if-no-files-found: error
      - if: github.event_name == 'release'
        name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./bin/sage-darwin-*
          file_glob: true
